### ISSUE TITLE
Ata da primeira reunião com Cliente

### ISSUE THREAD

**Issue by Messielly** [IF977/EasyMarket#2]
Registro do que será o problema a ser trabalhado no projeto.

[DocumentoES.docx.docx](https://github.com/IF977/EasyMarket/files/215717/DocumentoES.docx.docx)

**Comment by SandrineMartins** [comment]
Esse documento não é uma ata. Pode usar esse exemplo e adaptar a necessidade de vocês
[](http://escritoriodeprojetos.com.br/component/jdownloads/send/8-modelos/8-ata-de-reuniao)

**Comment by Messielly** [comment]
Ata da reunião.

[Ata de Reunião com o Cliente -  EasyMarket.docx.docx](https://github.com/IF977/EasyMarket/files/217769/Ata.de.Reuniao.com.o.Cliente.-.EasyMarket.docx.docx)

**Comment by Messielly** [comment]
Estamos com dúvida em relação:

Às "ações a serem tomadas", colocamos ações de acordo com o Syllabus de ES. Podemos fazer isso?

Ao "patrocinador do projeto", colocamos o CIn como sendo o nosso. Podemos colocá-lo realmente?

Ata de Reunião com o Cliente - EasyMarket.docx.docx

**Comment by Messielly** [comment]
Ata corrigida. @SandrineMartins  

[Ata.de.Reuniao.com.o.Cliente.-.EasyMarket.docx.docx](https://github.com/IF977/EasyMarket/files/218170/Ata.de.Reuniao.com.o.Cliente.-.EasyMarket.docx.docx)
